# Generated by Django 5.0.4 on 2024-04-17 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('idPerson', models.AutoField(primary_key=True, serialize=False)),
                ('documentId', models.CharField(max_length=20)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('mail', models.CharField(max_length=100, unique=True)),
                ('dateOfBirth', models.DateField()),
                ('personType', models.CharField(choices=[('A', 'Admin'), ('E', 'Empleado'), ('S', 'Estudiante'), ('G', 'Graduado'), ('V', 'Visitante')], max_length=1)),
                ('password', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('idVehicle', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
                ('rate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('idCard', models.AutoField(primary_key=True, serialize=False)),
                ('balance', models.IntegerField()),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='A', max_length=1)),
                ('idPerson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uparkapp.person')),
            ],
        ),
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('idPay', models.AutoField(primary_key=True, serialize=False)),
                ('transactionValue', models.IntegerField()),
                ('cusCod', models.CharField(max_length=7)),
                ('date', models.DateTimeField()),
                ('idPerson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uparkapp.person')),
                ('idVehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='uparkapp.vehicle')),
            ],
        ),
    ]
