# Generated by Django 5.0.2 on 2024-02-26 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uparkapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('idVehicle', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
                ('rate', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='personType',
            field=models.CharField(choices=[('E', 'Empleado'), ('S', 'Estudiante'), ('G', 'Graduado'), ('V', 'Visitante')], max_length=10),
        ),
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('idPay', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('transactionValue', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('idPerson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uparkapp.person')),
                ('idVehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uparkapp.vehicle')),
            ],
        ),
    ]
