# Generated by Django 5.0.4 on 2024-04-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uparkapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='documentId',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
