# Generated by Django 5.0.2 on 2024-02-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uparkapp', '0002_vehicle_alter_person_persontype_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='idCard',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pay',
            name='idPay',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='idVehicle',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
