# Generated by Django 5.0.2 on 2024-03-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uparkapp', '0004_alter_pay_date_alter_person_persontype'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='cusCod',
            field=models.CharField(default=0, max_length=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pay',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
