# Generated by Django 5.0.2 on 2024-03-11 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uparkapp', '0006_person_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='idCard',
        ),
        migrations.AddField(
            model_name='card',
            name='idPerson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='uparkapp.person'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='A', max_length=10),
        ),
    ]
