# Generated by Django 5.0.2 on 2024-03-13 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uparkapp', '0007_remove_person_idcard_card_idperson_card_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay',
            name='idVehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='uparkapp.vehicle'),
        ),
    ]
