# Generated by Django 5.0.2 on 2024-03-19 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uparkapp', '0008_alter_pay_idvehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='mail',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
