# Generated by Django 5.0.2 on 2024-03-19 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uparkapp', '0010_alter_person_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='password',
            field=models.CharField(max_length=140),
        ),
    ]
